{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apogee.fullname" . }}-secrets
  labels:
    {{- include "apogee.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "apogee.databaseUrl" . | quote }}
  {{- if .Values.secrets.sessionSecret }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.oidcClientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secrets.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
